services:
  - type: web
    name: drvyn-backend
    runtime: python
    pythonVersion: "3.10.10"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://drvynin:y3WC396ehtHraxQo@drvyn.tvqibqf.mongodb.net/?retryWrites=true&w=majority&appName=Drvyn
      - key: DB_NAME
        value: carbrands